name: CI Pipeline

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - '.github/**'
  push:
    branches: [ main, develop ]
    paths: 
      - 'src/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore -v m
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build -v m --source /home/runner/work/diddy-backend/diddy-backend/src/lambdas/Common/bin/Release/ --configuration Release
      working-directory: ${{env.working-directory}}
